package template_test

import (
	"testing"
	"time"

	"github.com/linuxsuren/gogit/argoworkflow/template"
	"github.com/stretchr/testify/assert"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func TestCommentTemplate(t *testing.T) {
	var layout string = "2006-01-02 15:04:05"
	var timeStr string = "2019-12-12 15:22:12"
	targetTime, err := time.ParseInLocation(layout, timeStr, time.Local)
	assert.Nil(t, err)

	startTime := v1.Time{Time: targetTime}
	endTime := v1.Time{Time: startTime.Add(time.Second * 5)}

	node1 := map[string]interface{}{"Phase": "Success", "DisplayName": "node-1", "StartedAt": startTime, "FinishedAt": endTime, "StartedTime": "2023-01-06T07:49:07Z", "EndedTime": "2023-01-06T07:54:26Z"}
	node2 := map[string]interface{}{"Phase": "Failed", "DisplayName": "node-2", "StartedAt": startTime, "FinishedAt": endTime, "StartedTime": "2023-01-06T07:49:07Z", "EndedTime": "2023-01-06T07:54:26Z"}
	// TODO cannot handle the situation in template
	// node3 := map[string]interface{}{"DisplayName": "node-2.OnExit"}
	// node4 := map[string]interface{}{"DisplayName": "plugin-8bs4n.hooks.all"}

	nodes := map[string]interface{}{}
	nodes["node1"] = node1
	nodes["node2"] = node2
	// nodes["node3"] = node3
	// nodes["node4"] = node4

	status := map[string]interface{}{}
	status["Nodes"] = nodes
	status["Phase"] = "Failed"
	status["StartedAt"] = startTime
	status["FinishedAt"] = endTime

	object := map[string]interface{}{}
	object["Status"] = status
	object["Annotations"] = map[string]string{
		"workflow.link":         "https://github.com/linxusuren/gogit",
		"workflow.templatelink": "https://github.com/linxusuren/gogit.git",
	}
	object["Spec"] = map[string]interface{}{
		"WorkflowTemplateRef": map[string]string{
			"Name": "Sample",
		},
	}

	result, err := template.RenderTemplate(template.CommentTemplate, object)
	assert.Nil(t, err)
	assert.Equal(t, `
<!-- Generated by https://github.com/LinuxSuRen/gogit -->
[Sample](https://github.com/linxusuren/gogit.git) is Failed. It started from 12-12 15:22, and took 5s. Please check log output from [here](https://github.com/linxusuren/gogit).

| Stage | Status | Duration |
|---|---|---|
| node-1 | Success | 5s |
| node-2 | Failed | 5s |
`, result)

	result, err = template.RenderTemplate(`
<!-- Generated by https://github.com/LinuxSuRen/gogit -->
| Stage | Status | Duration |
|---|---|---|
{{ range $node, $status := .Status.Nodes -}}
| {{$status.DisplayName}} | {{$status.Phase}} | {{durationStr $status.EndedTime $status.StartedTime}} |
{{end -}}
`, object)
	assert.Nil(t, err)
	assert.Equal(t, `
<!-- Generated by https://github.com/LinuxSuRen/gogit -->
| Stage | Status | Duration |
|---|---|---|
| node-1 | Success | 5m19s |
| node-2 | Failed | 5m19s |
`, result)
}

func TestOutput(t *testing.T) {
	objects := map[string]template.OutputObject{}
	objects["test"] = template.OutputObject{
		Kind:     template.FileOutput,
		File:     "https://github.com",
		FileName: "install.yaml",
	}
	objects["string"] = template.OutputObject{
		Kind:  template.ValueOutput,
		Value: "ghcr.io/linuxsuren/gogit",
	}
	objects["report_md"] = template.OutputObject{
		Kind:  template.MarkdownOutput,
		Value: "## title",
	}

	result, err := template.RenderTemplate(template.OutputsTemplate, objects)
	assert.Nil(t, err)
	assert.Equalf(t, `
<!-- Generated by https://github.com/LinuxSuRen/gogit -->
Please feel free to check the following outputs:

| Output |
|---|
| string: ghcr.io/linuxsuren/gogit |
| [install.yaml](https://github.com) |


## title
`, result, result)
}
